version: '3'

services:
  uw-mailman3-core:
    restart: always
    container_name: uw-mailman3-core
    hostname: uw-mailman3-core
    build:
      context: ../uw-mailman3-core
    environment:
      ENV: localdev
      MAILMAN_HOSTNAME: uw-mailman3-core
      SMTP_HOST: 127.0.0.1
      MAILMAN_ADMIN_USER: restadmin
      MAILMAN_ADMIN_PASSWORD: restpass
      MAILMAN_SITE_OWNER: javerage@uw.edu
      HYPERKITTY_API_KEY: "someapikey"

  uw-mailman3-web:
    restart: always
    container_name: uw-mailman3-web
    build:
      context: .
    volumes:
    - ./uwtheme:/app/uwtheme
    ports:
     - "${PORT:-8001}:8000"
     - "8080:8080"
    stdin_open: true
    tty: true
    environment:
      ENV: localdev
      AUTH: SAML_MOCK
      LOGIN_URL: saml_login
      LOGOUT_URL: saml_logout
      MAILMAN_ARCHIVER_FROM: uw-mailman3-core
      MAILMAN_REST_URL: http://uw-mailman3-core:8000
      MAILMAN_REST_USER: restadmin
      MAILMAN_REST_PASSWORD: restpass
    #- AUTH: ${AUTH:-SAML_DJANGO_LOGIN}
    #- DJANGO_LOGIN_USERNAME: ${DJANGO_LOGIN_USERNAME:-javerage}
    #- DJANGO_LOGIN_PASSWORD: ${DJANGO_LOGIN_PASSWORD:-javerage}
    #- DJANGO_LOGIN_EMAIL: ${DJANGO_LOGIN_EMAIL:-javerage@uw.edu}
      HYPERKITTY_API_KEY: "someapikey"
      THEME_OFF: ${THEME_OFF:-false}
