version: '3'

services:
  uw-mailman3-core:
    restart: always
    container_name: uw-mailman3-core
    hostname: uw-mailman3-core
    build:
      context: ../uw-mailman3-core
    ports:
     - "8000:8000"
    environment:
      ENV: localdev
      HYPERKITTY_CONFIG_TEMPLATE: |
        [general]
        base_url: http://uw-mailman3-web:8080/hyperkitty/
        api_key: someapikey
      MAILMAN_CONFIG_TEMPLATE: |
        [paths.master]
        var_dir: /app/mailman/var
        [database]
        url: sqlite:////app/mailman/sqlite.db
        [runner.retry]
        sleep_time: 10s
        [webservice]
        hostname: uw-mailman3-core
        port: 8000
        admin_user: restadmin
        admin_pass: restpass
        configuration: /app/mailman/var/etc/gunicorn.cfg
        [archiver.hyperkitty]
        class: mailman_hyperkitty.Archiver
        enable: yes
        configuration: /app/mailman/var/etc/mailman-hyperkitty.cfg
        [mta]
        incoming: mailman.mta.postfix.LMTP
        outgoing: mailman.mta.deliver.deliver
        lmtp_host: 127.0.0.1
        lmtp_port: 8024
        smtp_host: 127.0.0.1
        smtp_port: 25
        configuration: /app/mailman/var/etc/postfix-mailman.cfg
        [mailman]
        site_owner: javerage@uw.edu
        [logging.root]
        path: /dev/stdout
        [logging.archiver]
        path: /dev/stdout
        [logging.bounce]
        path: /dev/stdout
        [logging.config]
        path: /dev/stdout
        [logging.database]
        path: /dev/stdout
        [logging.debug]
        path: /dev/stdout
        [logging.error]
        path: /dev/stdout
        [logging.fromusenet]
        path: /dev/stdout
        [logging.http]
        path: /dev/stdout
        [logging.mischief]
        path: /dev/stdout
        [logging.plugins]
        path: /dev/stdout
        [logging.rest]
        path: /dev/stdout
        [logging.runner]
        path: /dev/stdout
        [logging.smtp]
        path: /dev/stdout
        [logging.subscribe]
        path: /dev/stdout
        [logging.task]
        path: /dev/stdout
        [logging.template]
        path: /dev/stdout
        [logging.vette]
        path: /dev/stdout
      POSTFIX_CONFIG_TEMPLATE: |
        [postfix]
        transport_file_type: regex
        postmap_command: true
      GUNICORN_CONFIG_TEMPLATE: |
        [gunicorn]
        graceful_timeout = 30
        timeout = 360
    command: >-
      /bin/bash
      -c
      'echo "$$MAILMAN_CONFIG_TEMPLATE" > /config/mailman.tpl;
       echo "$$HYPERKITTY_CONFIG_TEMPLATE" > /config/mailman-hyperkitty.tpl;
       echo "$$POSTFIX_CONFIG_TEMPLATE" > /config/postfix-mailman.tpl;
       echo "$$GUNICORN_CONFIG_TEMPLATE" > /config/gunicorn.tpl;
       /scripts/start.sh'

  uw-mailman3-web:
    restart: always
    container_name: uw-mailman3-web
    build:
      context: .
    volumes:
    - ./uwtheme:/app/uwtheme
    ports:
     - "8080:8080"
    stdin_open: true
    tty: true
    environment:
      PORT: 8080
      ENV: localdev
      AUTH: SAML_MOCK
      LOGIN_URL: saml_login
      LOGOUT_URL: saml_logout
      MAILMAN_ARCHIVER_FROM: uw-mailman3-core
      MAILMAN_REST_URL: http://uw-mailman3-core:8000
      MAILMAN_REST_USER: restadmin
      MAILMAN_REST_PASSWORD: restpass
    #- AUTH: ${AUTH:-SAML_DJANGO_LOGIN}
    #- DJANGO_LOGIN_USERNAME: ${DJANGO_LOGIN_USERNAME:-javerage}
    #- DJANGO_LOGIN_PASSWORD: ${DJANGO_LOGIN_PASSWORD:-javerage}
    #- DJANGO_LOGIN_EMAIL: ${DJANGO_LOGIN_EMAIL:-javerage@uw.edu}
      HYPERKITTY_API_KEY: "someapikey"
      THEME_OFF: ${THEME_OFF:-false}
