version: '3'

services:
  uw-mailman3-core:
    restart: always
    container_name: uw-mailman3-core
    build:
      context: ../uw-mailman3-core
    networks:
      mailman:
        ipv4_address: 172.19.199.2

  uw-mailman3-web:
    restart: always
    container_name: uw-mailman3-web
    build:
      context: .
    volumes:
      - ./mmtheme:/app/mmtheme
    ports:
      - "${PORT:-8000}:8000"
      - "8080:8080"
    stdin_open: true
    tty: true
    environment:
      ENV: localdev
      #AUTH: ${AUTH:-SAML_DJANGO_LOGIN}
      #DJANGO_LOGIN_USERNAME: ${DJANGO_LOGIN_USERNAME:-javerage}
      #DJANGO_LOGIN_PASSWORD: ${DJANGO_LOGIN_PASSWORD:-javerage}
      #DJANGO_LOGIN_EMAIL: ${DJANGO_LOGIN_EMAIL:-javerage@uw.edu}
      MAILMAN_HOST_IP: 172.19.199.2
      MAILMAN_HOSTNAME: ${MAILMAN_HOSTNAME:-uw-mailman3-core}
    networks:
      mailman:
        ipv4_address: 172.19.199.3

networks:
   mailman:
     driver: bridge
     ipam:
       driver: default
       config:
       -
         subnet: 172.19.199.0/24
