autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
ingress:
  enabled: true
  type: nginx
  tls:
    test-mailman-web:
      secretName: test.lists.uw.edu-ingress-cert
      hosts:
        - test.lists.uw.edu
    test01-mailman-web:
      secretName: test01.lists.uw.edu-ingress-cert
      hosts:
        - test01.lists.uw.edu
  hosts:
    test-mailman-web:
      host: test.lists.uw.edu
      paths:
        - "/"
    test01-mailman-web:
      host: test01.lists.uw.edu
      paths:
        - "/"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
deploymentInitialization:
  enabled: true
  finishedJobTTL: 300
securityPolicy:
  enabled: true
readiness:
  enabled: true
database:
  engine: postgres
  name: mailmanweb
  hostname: mailman-web-01-db-test-service
  secretName: test01.lists.uw.edu-sql-secret
externalService:
  enabled: true
  name: mailman-web-01-db-test-service
  type: ClusterIP
  serviceAddress: 172.18.1.64
  servicePort: 5432
repo: mailman-web
repoIdentifier: "01"
instance: test
namespace:
  enabled: true
  name: mailman-test
  suppressDefinition: true
resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 50m
    memory: 256Mi
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
  pushgateway:
    enabled: false
certs:
  mounted: true
  certPath: /certs/test01.lists.uw.edu.cert
  keyPath: /certs/test01.lists.uw.edu.key
  secretName: test01.lists.uw.edu-ic-certs
podVolumes:
  mailman-core-pvc-opt-mailman-web-data:
    persistentVolumeClaim:
      claimName: mailman-core-01-pvc-opt-mailman-web-data-mailman-core-01-0
    mount:
      mountPath: /opt/mailman-web-data
      subPath: "01"
    containers: [ base ]
environmentVariables:
  - name: ENV
    value: dev
  - name: AUTH
    value: SAML
  - name: LOGIN_URL
    value: saml_login
  - name: LOGOUT_URL
    value: saml_logout
  - name: MAILMAN_REST_URL
    value: http://mailman-core-01
  - name: MAILMAN_ARCHIVER_FROM
    value: mailman-core-01
  - name: CLUSTER_CNAME
    value: test01.lists.uw.edu
  - name: SAML_ENTITY_ID
    value: https://test01.lists.uw.edu/sso/
  - name: POSTORIUS_TEMPLATE_BASE_URL
    value: https://test01.lists.uw.edu/

externalSecrets:
  enabled: true
  secrets:
    - name: test01.lists.uw.edu-shared-secrets
      externalKey: mailman/shared/test/secrets
      data:
        - name: mailman-rest-user
          property: mailman-admin-user
        - name: mailman-rest-password
          property: mailman-admin-password
        - name: hyperkitty-api-key
          property: hyperkitty-api-key
    - name: test01.lists.uw.edu-secrets
      externalKey: mailman/web/test/secrets
      data:
        - name: django-secret
          property: django-secret
        - name: email-host
          property: email-host
        - name: default-from-email
          property: default-from-email
        - name: mailman2-rest-key
          property: mailman2-rest-key
    - name: test01.lists.uw.edu-sql-secret
      externalKey: mailman/web/test/sql-secret
      data:
        - name: username
          property: sql_user
        - name: password
          property: sql_pass
    - name: test01.lists.uw.edu-ic-certs
      externalKey: mailman/web/test/01/ic-certs
      data:
        - name: test01.lists.uw.edu.cert
          property: cert
        - name: test01.lists.uw.edu.key
          property: key
    - name: test01.lists.uw.edu-uw-idp-cert
      externalKey: idp-cert
      data:
        - name: uw-idp-cert
          property: cert
environmentVariablesSecrets:
  djangoSecret:
    name: DJANGO_SECRET
    secretName: test01.lists.uw.edu-secrets
    secretKey: django-secret
  emailHost:
    name: EMAIL_HOST
    secretName: test01.lists.uw.edu-secrets
    secretKey: email-host
  defaultFromEmail:
    name: DEFAULT_FROM_EMAIL
    secretName: test01.lists.uw.edu-secrets
    secretKey: default-from-email
  mailman2RestKey:
    name: RESTCLIENTS_MAILMAN2_REST_KEY
    secretName: test01.lists.uw.edu-secrets
    secretKey: mailman2-rest-key
  mailmanAdminUser:
    name: MAILMAN_REST_USER
    secretName: test01.lists.uw.edu-shared-secrets
    secretKey: mailman-rest-user
  mailmanAdminPassword:
    name: MAILMAN_REST_PASSWORD
    secretName: test01.lists.uw.edu-shared-secrets
    secretKey: mailman-rest-password
  hyperkittyAPIKey:
    name: HYPERKITTY_API_KEY
    secretName: test01.lists.uw.edu-shared-secrets
    secretKey: hyperkitty-api-key
  SAMLServiceProviderCert:
    name: SP_CERT
    secretName: test01.lists.uw.edu-ic-certs
    secretKey: test01.lists.uw.edu.cert
  SAMLIDPCert:
    name: IDP_CERT
    secretName: test01.lists.uw.edu-uw-idp-cert
    secretKey: uw-idp-cert
