autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
ingress:
  enabled: true
  type: nginx
  tls:
    test-mailman-web:
      secretName: test.lists.uw.edu-ingress-cert
      hosts:
        - test.lists.uw.edu
  hosts:
    test-mailman-web:
      host: test.lists.uw.edu
      paths:
        - "/"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
securityPolicy:
  enabled: true
readiness:
  enabled: true
database:
  engine: postgres
  name: mailmanweb
  hostname: mailman-web-db-test-service
  secretName: test.lists.uw.edu-sql-secret
externalService:
  enabled: true
  name: mailman-web-db-test-service
  type: ClusterIP
  serviceAddress: 172.18.1.64
  servicePort: 5432
repo: mailman-web
instance: test
resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 50m
    memory: 256Mi
image:
  repository: gcr.io/uwit-mci-axdd/mailman-web
  tag: IMAGE_TAG
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
  pushgateway:
    enabled: false
environmentVariables:
  - name: ENV
    value: dev
  - name: AUTH
    value: SAML
  - name: LOGIN_URL
    value: saml_login
  - name: LOGOUT_URL
    value: saml_logout
  - name: MAILMAN_REST_URL
    value: http://mailman-core-prod-test
  - name: MAILMAN_ARCHIVER_FROM
    value: mailman-core-prod-test
  - name: DATABASE_HOSTNAME
    value: "mailman-web-db-test-service"
  - name: DATABASE_DB_NAME
    value: "mailmanweb"
  - name: CLUSTER_CNAME
    value: test.lists.uw.edu
externalSecrets:
  enabled: true
  secrets:
    - name: test.lists.uw.edu-shared-secrets
      externalKey: axdd/kv/data/mailman/shared/test/secrets
      data:
        - name: mailman-rest-user
          property: mailman-admin-user
        - name: mailman-rest-password
          property: mailman-admin-password
        - name: hyperkitty-api-key
          property: hyperkitty-api-key
    - name: test.lists.uw.edu-secrets
      externalKey: axdd/kv/data/mailman/web/test/secrets
      data:
        - name: django-secret
          property: django-secret
    - name: test.lists.uw.edu-sql-secret
      externalKey: axdd/kv/data/mailman/web/test/sql-secret
      data:
        - name: username
          property: sql_user
        - name: password
          property: sql_pass
    - name: test.lists.uw.edu-ic-certs
      externalKey: axdd/kv/data/mailman/web/test/ic-certs
      data:
        - name: test.lists.uw.edu.cert
          property: cert
    - name: test.lists.uw.edu-uw-idp-cert
      externalKey: axdd/kv/data/idp-cert
      data:
        - name: uw-idp-cert
          property: cert
environmentVariablesSecrets:
  djangoSecret:
    name: DJANGO_SECRET
    secretName: test.lists.uw.edu-secrets
    secretKey: django-secret
  mailmanAdminUser:
    name: MAILMAN_REST_USER
    secretName: test.lists.uw.edu-shared-secrets
    secretKey: mailman-rest-user
  mailmanAdminPassword:
    name: MAILMAN_REST_PASSWORD
    secretName: test.lists.uw.edu-shared-secrets
    secretKey: mailman-rest-password
  hyperkittyAPIKey:
    name: HYPERKITTY_API_KEY
    secretName: test.lists.uw.edu-shared-secrets
    secretKey: hyperkitty-api-key
  SAMLServiceProviderCert:
    name: SP_CERT
    secretName: test.lists.uw.edu-ic-certs
    secretKey: test.lists.uw.edu.cert
  SAMLIDPCert:
    name: IDP_CERT
    secretName: test.lists.uw.edu-uw-idp-cert
    secretKey: uw-idp-cert
